apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: capstone-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - name: capstone-project
          image: roopendra123/capstone_project:v1
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: NodePort
  selector:
    app: capstone-project
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007  # Minikube will map this port
